# So Fifa

In [1]:
import sys

sys.path.append("../../")
import penaltyblog as pb
import pandas as pd
from time import sleep

## Instantiate the scraper

In [2]:
sofifa = pb.scrapers.SoFifa()

## Get top-level player data (sorted on player potential high to low)

In [3]:
player_info = sofifa.get_players(max_pages=1, sort_by="potential")

player_info.head()

,name,url,nationality,team,age,overall_rating,potential,value,wage,total,positions
id,,,,,,,,,,,
231747,Kylian Mbappé,/player/231747/kylian-mbappe/220069/,France,Paris Saint-Germain,22,91,95,€194M,€230K,2175,"[ST, LW]"
239085,Erling Haaland,/player/239085/erling-haaland/220069/,Norway,Borussia Dortmund,20,88,94,€143.5M,€110K,2120,[ST]
251854,Pedro González López,/player/251854/pedro-gonzalez-lopez/220069/,Spain,FC Barcelona,18,84,92,€88.5M,€66K,2096,[CM]
237692,Phil Foden,/player/237692/phil-foden/220069/,England,Manchester City,21,84,92,€94.5M,€140K,2073,"[LW, CF, CAM]"
230621,Gianluigi Donnarumma,/player/230621/gianluigi-donnarumma/220069/,Italy,Paris Saint-Germain,22,88,92,€106M,€110K,1375,[GK]

## Get top-level player data (sorted on player age low to high)

In [4]:
player_info = sofifa.get_players(max_pages=1, sort_by="value", sort_direction="asc")

player_info.head()

,name,url,nationality,team,age,overall_rating,potential,value,wage,total,positions
id,,,,,,,,,,,
257536,Jan Kuchta,/player/257536/jan-kuchta/220069/,Czech Republic,None,24,77,80,€0,€0,1923,"[ST, CAM]"
242953,Nikko Boxall,/player/242953/nikko-boxall/220069/,New Zealand,None,29,62,62,€0,€0,1475,"[CB, CDM]"
236298,Eduard Atuesta,/player/236298/eduard-atuesta/220069/,Colombia,None,24,75,82,€0,€0,1976,"[CDM, CM]"
242954,Niko Kirwan,/player/242954/niko-kirwan/220069/,New Zealand,None,25,64,66,€0,€0,1691,"[RB, LB, RM]"
140814,Stavros Georgiou,/player/140814/stavros-georgiou/220069/,Cyprus,None,16,53,68,€0,€0,1436,"[CF, RW, LW]"

## Get top-level player data (sorted on player value high to low)

In [5]:
player_info = sofifa.get_players(max_pages=1, sort_by="value")

player_info.head()

,name,url,nationality,team,age,overall_rating,potential,value,wage,total,positions
id,,,,,,,,,,,
231747,Kylian Mbappé,/player/231747/kylian-mbappe/220069/,France,Paris Saint-Germain,22,91,95,€194M,€230K,2175,"[ST, LW]"
239085,Erling Haaland,/player/239085/erling-haaland/220069/,Norway,Borussia Dortmund,20,88,94,€143.5M,€110K,2120,[ST]
209331,Mohamed Salah,/player/209331/mohamed-salah/220069/,Egypt,Liverpool,29,91,91,€129M,€350K,2236,[RW]
192985,Kevin De Bruyne,/player/192985/kevin-de-bruyne/220069/,Belgium,Manchester City,30,91,91,€125.5M,€350K,2303,"[CM, CAM]"
228702,Frenkie de Jong,/player/228702/frenkie-de-jong/220069/,Netherlands,FC Barcelona,24,87,92,€119.5M,€210K,2234,[CM]

## Get detailed player data

In [6]:
players = list()
for id_ in player_info.index[:5]:
    tmp = sofifa.get_player(id_)
    players.append(tmp)
    sleep(1)
    
players = pd.concat(players)
players

,name,weight,height,age,position,overall_rating,potential,value,wage,preferred_foot,...,mentality_composure,defending_defensive_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_gk_diving,goalkeeping_gk_handling,goalkeeping_gk_kicking,goalkeeping_gk_positioning,goalkeeping_gk_reflexes,traits
0,Kylian Mbappé Lottin,73,182,22,LS,91,95,€194M,€230K,Right,...,88,26,34,32,13,5,7,11,6,"[Solid Player, Flair, Speed Dribbler (AI), Out..."
0,Erling Braut Haaland,94,194,20,ST,88,94,€143.5M,€110K,Left,...,85,44,53,29,7,14,13,11,7,"[Injury Prone, Speed Dribbler (AI), Power Header]"
0,Mohamed Salah Ghaly,71,175,29,RW,91,91,€129M,€350K,Left,...,92,38,43,41,14,14,9,11,14,"[Finesse Shot, Long Shot Taker (AI), Speed Dri..."
0,Kevin De Bruyne,70,181,30,RM,91,91,€125.5M,€350K,Right,...,89,68,65,53,15,13,5,10,13,"[Injury Prone, Leadership, Early Crosser, Long..."
0,Frenkie de Jong,74,180,24,LCM,87,92,€119.5M,€210K,Right,...,90,76,76,77,7,13,10,10,9,"[Flair, Playmaker (AI), Outside Foot Shot, Tec..."